"""Type stubs for m_vllm_csrc compiled module"""

def add(a: int, b: int) -> int:
    """Add two integers"""
    ...

class Calculator:
    """Simple calculator class"""
    def __init__(self, init_value: int) -> None: ...
    def add(self, x: int) -> None: ...
    def get(self) -> int: ...
